<?php

namespace App\Modules\AILearning\Repositories;

use App\Modules\ContentManagement\Models\KnowledgeBase;
use App\Modules\AILearning\Models\ConversationContext;
use App\Modules\AILearning\Models\AIResponse;

class KnowledgeRepository
{
    /**
     * Search the student's extracted text using keywords.
     * 
     * @param int $userId
     * @param array $keywords - Generated by NLPProcessor
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function searchByKeywords($userId, array $keywords)
    {
        // Safety check: if NLP didn't find keywords, return empty result
        if (empty($keywords)) {
            return collect([]);
        }

        // Search KnowledgeBase entries belonging to this user
        return KnowledgeBase::whereHas('uploadedMaterial', function ($q) use ($userId) {
            // Security: Only search files owned by this user
            $q->where('user_id', $userId);
        })
            ->where(function ($q) use ($keywords) {
                // Dynamic OR WHERE loop for keywords
                foreach ($keywords as $word) {
                    // Search for the keyword inside the text content
                    $q->orWhere('content_text', 'LIKE', "%{$word}%");
                }
            })
            ->limit(3) // Optimization: Only retrieve top 3 matching chunks
            ->get();
    }

    /**
     * Log the conversation details to the database.
     * 
     * @param int $userId
     * @param string $query - The user's original question
     * @param string $response - The AI's answer
     * @param array $sources - IDs of the files used for context
     */
    public function logInteraction($userId, $query, $response, $sources)
    {
        // 1. Get or Create a default conversation context
        // (In the future, you can pass a conversation_id from the frontend to support threads)
        $context = ConversationContext::firstOrCreate(
            ['user_id' => $userId],
            ['context_name' => 'General Chat']
        );

        // 2. Save the interaction record
        return AIResponse::create([
            'user_id' => $userId,
            'conversation_id' => $context->id,
            'user_query' => $query,
            'ai_response' => $response,
            'confidence_score' => 0.85, // Placeholder (Gemini doesn't give a score easily)
            'sources' => $sources // Casts to JSON automatically via Model
        ]);
    }
}
