<?php

namespace App\Modules\AILearning\Repositories;

use App\Modules\ContentManagement\Models\KnowledgeBase;
use App\Modules\AILearning\Models\ConversationContext;
use App\Modules\AILearning\Models\AIResponse;
use Illuminate\Support\Str;

class KnowledgeRepository
{
    /**
     * Search the student's extracted text using keywords.
     * 
     * @param int $userId
     * @param array $keywords - Generated by NLPProcessor
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function searchByKeywords($userId, array $keywords)
    {
        // Safety check: if NLP didn't find keywords, return empty result
        if (empty($keywords)) {
            return collect([]);
        }

        // Search KnowledgeBase entries belonging to this user
        return KnowledgeBase::whereHas('uploadedMaterial', function ($q) use ($userId) {
            // Security: Only search files owned by this user
            $q->where('user_id', $userId);
        })
            ->where(function ($q) use ($keywords) {
                // Dynamic OR WHERE loop for keywords
                foreach ($keywords as $word) {
                    // Search for the keyword inside the text content
                    $q->orWhere('content_text', 'LIKE', "%{$word}%");
                }
            })
            ->limit(3) // Optimization: Only retrieve top 3 matching chunks
            ->get();
    }

    /**
     * Log the conversation.
     * Handles Creating NEW chats or CONTINUING existing ones.
     */
    public function logInteraction($userId, $query, $response, $sources, $conversationId = null)
    {
        $context = null;

        if ($conversationId) {
            // Continue existing chat
            $context = ConversationContext::where('id', $conversationId)
                ->where('user_id', $userId)
                ->first();
        }

        // If no ID provided OR ID not found -> Create NEW Chat
        if (!$context) {
            $context = ConversationContext::create([
                'user_id' => $userId,
                'context_name' => substr($query, 0, 30) . '...', // Use first 30 chars as title
                'conversation_id' => Str::uuid(), // Generates unique string
            ]);
        }

        // Save the message linked to this specific context
        AIResponse::create([
            'user_id' => $userId,
            'conversation_id' => $context->id,
            'user_query' => $query,
            'ai_response' => $response,
            'confidence_score' => 0.85,
            'sources' => $sources
        ]);

        return $context; // Return the context so frontend knows the ID
    }

    /**
     * Get list of all chat sessions for the sidebar.
     */
    public function getUserConversations($userId)
    {
        return ConversationContext::where('user_id', $userId)
            ->orderBy('updated_at', 'desc')
            ->get(['id', 'context_name', 'created_at']);
    }
}
